version: '3.1'

services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: ideas
    ports:
      - "5432:5432"

    