@baseUrl = http://localhost:4000


### Get Users
GET {{baseUrl}}/api/users


### Register User
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "hanataro",
    "password": "hanataronopassword"
}

### Login User 
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "hanataro",
    "password": "hanataronopassword"
}

### Get Ideas
GET {{baseUrl}}/api/ideas


### Create Idea
# @name createIdea
POST {{baseUrl}}/api/ideas
Content-Type: application/json

{
    "idea": "my idea21",
    "description": "my idea21 description"
}

@ideaId = {{createIdea.response.body.$.id}}

### Get a Idea
GET {{baseUrl}}/api/ideas/{{ideaId}}

### Update Idea
PUT {{baseUrl}}/api/ideas/{{ideaId}}
Content-Type: application/json

{
    "idea": "update my idea21",
    "description": "update my idea21 description"
}

### Delete Idea
DELETE {{baseUrl}}/api/ideas/{{ideaId}}


### Error Not found page
GET {{baseUrl}}/err

