@baseUrl = http://localhost:4000


### Register User
# @name registerUser
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "komanechi",
    "password": "komanechipass"
}

@token = {{registerUser.response.body.$.token}}

### Login User 
# @name loginUser
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "komanechi",
    "password": "komanechipass"
}

@loginToken = {{loginUser.response.body.$.token}}

### Get Users
GET {{baseUrl}}/api/users
Authorization: Bearer {{loginToken}}



### Get Ideas
GET {{baseUrl}}/api/ideas
Authorization: Bearer {{loginToken}}


### Create Idea
# @name createIdea
POST {{baseUrl}}/api/ideas
Content-Type: application/json
Authorization: Bearer {{loginToken}}

{
    "idea": "my idea21",
    "description": "my idea21 description"
}

@ideaId = {{createIdea.response.body.$.id}}

### Get a Idea
GET {{baseUrl}}/api/ideas/{{ideaId}}
Authorization: Bearer {{loginToken}}

### Update Idea
PUT {{baseUrl}}/api/ideas/{{ideaId}}
Content-Type: application/json
Authorization: Bearer {{loginToken}}

{
    "idea": "update my idea21",
    "description": "update my idea21 description"
}

### Delete Idea
DELETE {{baseUrl}}/api/ideas/{{ideaId}}
Authorization: Bearer {{loginToken}}


### Error Not found page
GET {{baseUrl}}/err

